"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const stackoverflow_1 = require("./stackoverflow");
let system = new stackoverflow_1.default();
let user1 = system.createUser("manav", "manavsharma136@gmail.com");
let user2 = system.createUser("akash", "akash@gmail.com");
let user3 = system.createUser("harman", "harman@gmail.com");
let question1 = system.postQuestion("why rpc is not working properly", "rpc error", user1, []);
system.postQuestion("why blockchain is not working properly", "blockchain error", user1, []);
console.log(system.getQuestionsByUser(user1));
console.log("Next answer");
console.log(system.searchQuestionByKeyword("blockchain"));
let manav = "keyword search";
system.postAnswer("becuase blockchains are shit", user3, question1);
console.log("Answers are:", system.getAnswersOfQuesion(question1));
let answers = system.getAnswersOfQuesion(question1);
// console.log("Answer are",answers[0],answers[0].idCounter="3");
